// app/routes/login.tsx
import LoginForm from "~/components/LoginForm";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { useNavigate } from "@remix-run/react";

export async function action({ request }: { request: Request }) {
  const formData = await request.formData();
  const userData = Object.fromEntries(formData);

  const user = JSON.stringify(userData);
  console.log(user);
  return user;
}

const Login = () => {

  const navigate = useNavigate()

  return (
    <div className="w-screen h-screen flex justify-center items-center">
      <div className="w-1/2 h-fit border border-gray-500 shadow-lg shadow-gray-500 rounded-xl">
        <Tabs defaultValue="login" className="w-full p-3">
          <TabsList className="w-full h-2/3 flex justify-between">
            <TabsTrigger className="w-1/2" value="login">
              Login
            </TabsTrigger>
            <div onClick={()=>navigate("/register")} className="w-1/2 hover:cursor-pointer  text-base font-semibold flex justify-center items-center">
              Register
            </div>
          </TabsList>
          <TabsContent className="p-3" value="login">
            <LoginForm />
          </TabsContent>
        </Tabs>
        <div className="w-full flex justify-center items-center">
          <p className="font-bold self-center pb-4">or</p>
        </div>
        <div className="w-full justify-center items-center flex mb-5">
          <div className="hover:cursor-pointer hover:bg-sky-400 duration-200 ease-in-out w-2/3 p-3 bg-sky-500 flex justify-center items-center rounded-md">
            <p className="self-center text-white font-semibold">
              Sign in with Google
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Login;

// pages/login.vue
<template>
  <div class="h-screen w-screen flex items-center justify-center bg-sky-300">
    <div
      class="fixed w-fit top-0 right-0 p-8 text-black text-x cursor-pointer"
      @click="() => navigateTo('/')"
    >
      X
    </div>
    <div class="bg-white p-8 rounded shadow-md w-1/3">
      <div
        v-if="select == 'register'"
        class="w-full h-full flex bg-white flex-col justify-center items-center"
      >
        <RegisterForm />
        <button class="mt-5 hover:underline" @click="onSelect('login')">
          Already have an account? Click to login!
        </button>
      </div>
      <div
        v-else-if="select == 'login'"
        class="w-full h-full flex bg-white flex-col justify-center items-center"
      >
        <LoginForm />
        <button class="mt-5 hover:underline" @click="onSelect('register')">
          New user? Click to register!
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const select = ref("login");

const onSelect = (value: string) => {
  select.value = value;
};
</script>
